# Generated by Django 5.0.4 on 2024-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_task_remove_report_description_remove_report_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
