# Generated by Django 5.0.4 on 2024-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_report_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
